### ISSUE TITLE
Download of dictionaries fails, if lang-variant is missing.

### ISSUE THREAD

**Issue by bmix** [manisandro/gImageReader#133]
I am on Windows 10, gImageReader is installed in the default location, as suggested per the installer.
When I select "German" as the OCR language, it tells me, that the dictionary files are missing and offers to download them. And, indeed, it does so for de-DE, de-CH, de-AT. But when it comes to de-LU it does not find that file on the server, as it seems and stops the installation of the dictionary files. It also does not install those files (de-DE, de-CH, de-AT), it already found and successfully downloaded.

**Comment by manisandro** [comment]
I'm note sure where `de_LU` comes from? Indeed such a definition is not available in the dictionaries repository [1], but then it shouldn't even know about it? The strategy gImageReader uses for downloading spelling dictionaries is as follows:
- It takes the language code of the currently chosen language (i.e. `de_CH`)
- If the full code (i.e. `de_CH`) is available in the repository [1], it downloads all `*.dic` and `*.aff` files inside that folder
- Otherwise, if only the language part (i.e. `de`) is available in the repository, it downloads all `*.dic` and `*.aff` files inside that folder
- If also the second approach failed, dictionary autoinstallation fails with `No spelling dictionaries found for <code>`.

Given this, I'm missing a piece of the puzzle to understand where `de_LU` comes from and why it should stumble on it. First of all, how exactly does dictionary installation fail? (i.e. what error message etc).

[1] https://cgit.freedesktop.org/libreoffice/dictionaries/tree/

**Comment by bmix** [comment]
1. I start the app. The message "`Dictionary is missing. The spelling-dictionary for German ist not installed.`" (Translated from the German locale, which I am running)
2. Dictionaries in `C:\Program Files (x86)\gImageReader\share\myspell\dicts` are: `en_US.aff` and `en_US.dic`
3. Since gImageReader offers me to download the dictionaries, I do so.
4. The first status message now says: `Installing dictionaries for language de_LU`. Now it downloads those I mentioned, but fails with this:
![dict_err](https://cloud.githubusercontent.com/assets/310157/20031871/03d2f5ce-a37f-11e6-86f7-88b760c53d5f.jpg)

Upon closer inspection, it seems, that it does not try to download a `de_LU` file, but instead assumes the locale, for which it needs to download the files, is `de_LU`, which would be the German part of Luxembourg.
I just checked with my Windows settings. I have set 'Germany' as locale.

It just came to me, that it may be a ownership problem, so I started _gImageReader_ as Administrator. It now worked:
![dict_err-2](https://cloud.githubusercontent.com/assets/310157/20031943/864c2f4c-a380-11e6-8b46-5c85888260db.jpg)

The installed dictionaries now are:
en_US.dic
de_AT_frami.aff
de_AT_frami.dic
de_CH_frami.aff
de_CH_frami.dic
de_DE_frami.aff
de_DE_frami.dic
en_US.aff

So I see two things:

a) It can not install the dictionaries if run as normal user, since it installs the dictionaries into its own program-folder, which is write-protected for a user, even if the user has administrative rights. It must be run as `Administrator`.
b) The locale is falsley assumed to be `de_LU`, but this is just cosmetic and neglectable.
I am not very well known with Windows. I assume, that under Windows, one writes global dynamic application data to `C:\ProgramData\your_application` and local (user), to `%AppData%\Local\your_application`. Not sure, whether QT supports this out of the box.

**Comment by manisandro** [comment]
You can configure gImageReader to use user-local directories in the program options, then dictionaries and tesseract language definitions are indeed stored in %AppData%. Some Windows versions also have a "VirtualStore" which virtualizes the location beneath %ProgramFiles% below the user profile directory, storing files which the user is not allowed to write/modify in %ProgramFiles% there. (I don't know the details though, not being a Windows user).
So in your case it should suffice to switch to user-local directories and then things should work fine.

**Comment by bmix** [comment]
Yeah, just came back to this issue, when I realized this, wanted to edit my last reply :-) Sorry. So I close it.
