### ISSUE TITLE
Texts of the output PDF sticking together

### ISSUE THREAD

**Issue by threelegcat2015** [manisandro/gImageReader#135]
The words were correctly identified with OCR, but the output text layer of the PDF gets into a mess with words connected each other which are difficult to read. Would it be possible to assign specific fonts and font size to cope with this?
Here are the screenshots created from 3.1.99 and a created PDF with selected text from a paragraph. Notice that the gImageReader correctly identitfy the words separately:
![2016-11-13 11-13-15](https://cloud.githubusercontent.com/assets/13062920/20243473/6ba62670-a993-11e6-8bd2-500ca43f15fe.png)

![2016-11-13 11-12-37](https://cloud.githubusercontent.com/assets/13062920/20243462/12d09c06-a993-11e6-86f4-cb05237ea359.png)

**Comment by manisandro** [comment]
You can indeed assign individual font sizes when you click on a word in the item properties, currently though it is very cumbersome since you have to go them through one-by-one (I have a future plan to allow chaning the font size for an entire text-line/paragraph also).
However, in your situation, I'd recommend you enabled "Use detected font sizes" and then scale this font size as necessary in the PDF output dialog. You should be able to get a decent result with this strategy.

**Comment by threelegcat2015** [comment]
Thanks for your reply! I've already enabled "Use detected font sizes" option for the above samples, but anyway I could still be able to adjust the scale to 85% with the default Sans Regular font. An alternative is changing to another font such as Liberation serif. I'd suggest it'd be better to assign a relative narrower default fonts with gImageReader.

**Comment by manisandro** [comment]
Well the default font is just the system default, it but if you change it once it should remember the choice.

**Comment by threelegcat2015** [comment]
Would you implement for the future versions to improve the font detection, such as that of font metrics, styles(serif/sans serif), and well as charcter spacing so that the adjustment could be made more automatically?

**Comment by manisandro** [comment]
For the most part, it's tesseracts job to provide gImageReader this data. The one aspect I could improve is to use the detected font family instead of ignoring it (i.e. see the properties of any word item in the hOCR tree). However, from what I've seen up to now the detected font families can vary a lot even inside the same sentence, plus the font family description is not in a standard (say, CSS) format, so I'd need to hard-code a mapping from the tesseract names to well-know font family names, so overall I'm not sure it would help that much.

**Comment by threelegcat2015** [comment]
Thank you for your suggestions anyway!
