### ISSUE TITLE
bizarre lines on the output PDF

### ISSUE THREAD

**Issue by Golddouble** [manisandro/gImageReader#138]
Hello,

Version in use: 3.2.0

This was my input- PDF
[Input.pdf](https://github.com/manisandro/gImageReader/files/644658/Input.pdf)

I used the following settings to generate the output PDF:
![gimage einstellungen](https://cloud.githubusercontent.com/assets/13977359/21082224/809afaec-bfd7-11e6-8101-5a9e26fa125b.PNG)
And yes, my Input pdf was also 300dpi.

After the text recognize process I got a PDF with strange Lines. Look at this:
![gimage striche](https://cloud.githubusercontent.com/assets/13977359/21082231/9f4f488a-bfd7-11e6-8d11-12c495375c7c.PNG)

And this is the whole Output PDF:
[Output.pdf](https://github.com/manisandro/gImageReader/files/644663/Output.pdf)

**Comment by manisandro** [comment]
Hmm it looks like Qt's monochrome dithering algorithm is creating artifacts. I suppose the image is fine if you choose grayscale (albeit clearly the resulting document larger), right?

**Comment by Golddouble** [comment]
I did just a test with greyscale. And Yes with jpg 80% greyscale it looks perfect.

**Comment by manisandro** [comment]
I'll look at using the algorithm I use in the Gtk interface for the Qt interface also. Will post a test-build as soon as I have something.

**Comment by manisandro** [comment]
Fixed in 36b73445eb515266e0fb7db32b4aaacc296d07e4: you can now choose between threshold and diffuse dithering algorithms.

Threshold dithering simply chooses black on white depending on whether the corresponding grayscale pixel is closer to white or closer to black, and is therefore the best choice for images which were originally monochrome.

Diffuse dithering diffuses the quantization error to neighboring pixels, and is therefore the best choice for images which were originally grayscale or color.

**Comment by Golddouble** [comment]
Wow, it is perfect now. Thank you.
