### ISSUE TITLE
version 3.2.1 Vs version 3.2.0

### ISSUE THREAD

**Issue by rupurar** [manisandro/gImageReader#168]
Hi, i am using latest gimagereader v3.2.1. It’s fast and accurate than the previous one. but it can’t detect inverted commas properly. it detects both (“) and (”) as ("). also for others are same, eg. (‘) and (’) as ('). but previous version (3.2.0) can detect it properly. btw, i am using bengali language for image detection.

**Comment by manisandro** [comment]
Hi
Rather than gImagereader, this depends on the tesseract version gImageReader was compiled against, and on the tesseract traineddata files. If you are on Linux, check whether your distro updated tesseract inbetween. If you are on Windows, the tesseract version shouldn't have changed between 3.2.1 and 3.2.0, unless you downloaded the preview version compiled against tesseract-4.0-alpha. If so, try downloading the regular version.

**Comment by rupurar** [comment]
yes, i am using tesseract 4.0 alpha on windows. when i use ben.traineddata (LSTM) on v3.2.1 it shows that types of error. but other mobile application such as ‘text fairy’ detect inverted coomas using this traineddata. and even the previous version 3.2.0 also detect it. but v3.2.1 can't. so i think problem is not in tesseract traineddata, it may be on gimagereader. ☺ btw i know its on experimental stage.
which one is regular version?

**Comment by manisandro** [comment]
gImageReader does not perform any recognition, it simply takes the result from tesseract. The regular version is the one without the tesseract4.0.0.git2f10be5 suffix in https://github.com/manisandro/gImageReader/releases/tag/v3.2.1

**Comment by rupurar** [comment]
Yes, that's right, the problem is not in gImagereader. regular version is free from such kind of bug. but preview version (4 alpha) is relatively more accurate and less time consuming than the regular one. 
thank you.

**Comment by manisandro** [comment]
I suppose that's why tesseract-4.0 it's still in alpha stage ;)
