### ISSUE TITLE
Add multithreaded OCR

### ISSUE THREAD

**Issue by ZaMaZaN4iK** [manisandro/gImageReader#203]
We use in gImageReader Tesseract as OCR engine. I know we can run recognition into more than one thread (one recognition thread per page).

Is it possible to add it to gImageReader?

**Comment by manisandro** [comment]
In principle yes, but lots of work. Currently the ui gives the feedback to the user to which page is currently being processed by actually displaying it as it is being recognized. This for instance would not be possible anymore in multithreaded mode. I think it would be easier to investigate what needs to be done for tesseract to use OpenCL acceleration (beyond actually compiling tesseract with opencl support)  instead of adding multithreading to gImageReader itself.

**Comment by ZaMaZaN4iK** [comment]
I am not sure that OpenCL can improve speed significantly comparing to multithreading. 
In out OCR solution we use Tesseract in mutithread mode. And it's really good way for working with Tesseract.

**Comment by manisandro** [comment]
You mean running one tesseract instance per thread or that tesseract internally uses multiple threads?

**Comment by ZaMaZaN4iK** [comment]
One Tesseract instance per thread. Tesseract can't use multiple threads internally.

**Comment by manisandro** [comment]
Ok, so as I said, this will require quite a lot of work.

**Comment by ZaMaZaN4iK** [comment]
Yep. I think, we can start do it later. Reason of the improvement: if i want to create searchable PDF from simple PDF and my source PDF is huge book (smth like 100+ pages), multithread OCR will help us a lot of.

**Comment by manisandro** [comment]
Looks like tesseract 4 can be compiled with OpenMP support, so possibly we can spare ourselves the work on client side.

**Comment by ZaMaZaN4iK** [comment]
Should be compared in performace with Tesseract 4 without OpenMP.

**Comment by manisandro** [comment]
I'll defer this to tesseract.
