### ISSUE TITLE
Please add possibility to create searchable PDF with text overlay

### ISSUE THREAD

**Issue by geckolinux** [manisandro/gImageReader#27]
Hi there,

gImageReader is turning out really well. But it would be nice to have the option to OCR a PDF and save a PDF with searchable text in an invisible layer.

Thanks a lot!

**Comment by manisandro** [comment]
Yes this would definitely be a nice feature. Need to think about how to best do the GUI integration though. I suppose something like
- add a combobox next to the OCR button allowing the user to choose between text output and overlay output
- if text output is chosen, behavior is as it is currently
- if overlay output is chosen, instead of a text field in the output pane, display a pdf-viewer style widget, displaying, for each recognized source image, the unmodified image overlayed with text fields containing the recognized text. Though should it still be allowed to recognize only portions of an image, and if yes, how to detect whether the same portion has already been recognized? An approach would be, every time a certain page is recognized, to add it as a separate page to the output pane, regardless of whether such a page already exists.

Thoughts welcome.

**Comment by innir** [comment]
I think this is linked to the ideas in issue #30. The hOCR output could be used to create a search-able pdf. There is already a program available ([hocr2pdf](http://exactcode.de/site/open_source/exactimage/hocr2pdf/)) that does the job.

**Comment by manisandro** [comment]
As noted in issue #30, an initial implementation is now committed, but some work remains to be done.

**Comment by manisandro** [comment]
A first implementation should be pretty usable now.
