### ISSUE TITLE
Greek spelling dictionary not working for Greek text

### ISSUE THREAD

**Issue by coursera-rafal** [manisandro/gImageReader#278]
Hi,

I use version 3.2.3 on Windows 7 Professional.

I have "grc.traineddata" in "C:\Program Files (x86)\gImageReader\share\tessdata" and "el_GR.aff" and "el_GR.dic" in "C:\Program Files (x86)\gImageReader\share\myspell\dicts"

The text is being recognised quite sensibly, however, all Greek words are highlighted in red, it's not recognising the spelling of even the most common words. Moreover, when I click on "add to dictionary", the dictionary that is being updated is the "en.dic" in "C:\Users\rif\AppData\Local\enchant" (I've found it by performing a search for *.dic and sorting by date modified.

I've completely uninstalled support for the English language (both tessdata and dicts) but it made no difference.

Am I missing something obvious? 

Many thanks,
Rif

**Comment by manisandro** [comment]
Hi
If you are working in HOCR mode, there are a couple of issues in 3.2.3 which have since been fixed. Please try with this development build:

32bit: https://smani.fedorapeople.org/tmp/gImageReader_3.2.3_qt5_i686.exe
64bit: https://smani.fedorapeople.org/tmp/gImageReader_3.2.3_qt5_x86_64.exe

I'm hoping to do a new release soonish.

**Comment by coursera-rafal** [comment]
Works perfectly, thank you very much!
