### ISSUE TITLE
gimagereader-qt defaulted to en_ZW (Zimbabwe)

### ISSUE THREAD

**Issue by skierpage** [manisandro/gImageReader#331]
I installed gimagereader-qt.x86_64 3.2.99 on my Fedora 28 beta KDE spin using DNF, then launched it from the KDE application launcher

The menu bar defaulted to "Recognize all English (en_ZW)", which is English (Zimbabwe).

system-config-language says my default language is English (USA), the Formats system settings module says my region is "United States - American English (en_US)", and my shell's `LANG` environment variable is `en_US.UTF-8`. So I'm not sure why it picked Zimbabwean English.

**Comment by manisandro** [comment]
Actually currently gImageReader isn't so smart to pick the language based on the system locale, it just picks the first combination it comes across when you first launch it. Since it remembers your choice subsquent times, I'm not sure it's worth implementing some fancy logic - it really only affects the very first time you start the program.

**Comment by skierpage** [comment]
> it just picks the first combination it comes across when you first launch it

Hmm, weird that en_ZW is at the bottom of the list.

> I'm not sure it's worth implementing some fancy logic - it really only affects the very first time you start the program.

en_*SOMECODE* is quite technical. It encouraged me to click the dropdown menu to see other choices but I suspect most users will be puzzled by it and tune it out. Selecting the locale, if any, in the dropdown matching `QLocale().name()` the first time you run would do the right thing for many users. Low priority for sure.

**Comment by manisandro** [comment]
Actually it is the last combination it came accross, because as it traverses the languages, it checks whether one matches the stored setting, and if not, it will use the last one it traversed, see [1].

Suppose looking at QLocale could work, but then you have the problem that most of the time people will only have the english tessdata installed initially, so unless your locale is english, the logic won't work anyway.

[1] https://github.com/manisandro/gImageReader/blob/master/qt/src/Recognizer.cc#L176

**Comment by manisandro** [comment]
Closing since I don't believe there is anything concretely to do.
