### ISSUE TITLE
detect most suitable font size automaticly for output

### ISSUE THREAD

**Issue by napasa** [manisandro/gImageReader#356]
We have font size relevant option like font scaling, override font size when we export pdf, But I think that this step choose better font size should be finished by program. because most PDF have so much pages we have no time and no possible to check whether I have choose a right font size page by page. Perhaps the font size suits the first 10 pages and cause some word of the 11th page is draw out the paint device boundary.  So we should have mechanism to check whether the word is draw out the boundary, once circumstance like that happened, we should calculate out the better suitable font size to replace the value user set

**Comment by manisandro** [comment]
I don't really think this would work, as you'd assume the same text size everywhere and the worst fitting bounding box would determine the font size for the entire document, which would inevitably result in an odd looking result. I think the best bet is to have the use select the best matching font family and use the font sizes detected by the OCR engine, and if necessary you can set the font scaling factor when exporting to get the best possible match.

**Comment by manisandro** [comment]
Could be an idea, though the average size won't guarantee you that all words fit their bounding box, hence you'd still need to check the entire document if you want a "perfect" result. (Though to speed up checking, one could add a new entry "Overflowing word" to the navigation bar, so that the user can quickly find those.) Also, with averaging (or any other auto-detection scheme for the matter) you are likely to get slightly different font sizes for each paragraph, especially if the chosen font does not match the original font well, or the paragraphs contain few words. One could attempt to homogenize them by again averaging them if within a treshold, but finding sensible thresholds is likely document-dependent.

I'll look into it as time allows.

**Comment by manisandro** [comment]
Tracking in #449
