### ISSUE TITLE
Portable version

### ISSUE THREAD

**Issue by bup4gr** [manisandro/gImageReader#360]
Is it possible to add a portable version of gImageReader on release page https://github.com/manisandro/gImageReader/releases?

**Comment by gazeto** [comment]
Sorry, maybe I am just confused (because of talk of a 3.3.0 portable version above and [here](https://github.com/manisandro/gImageReader/issues/376)). But I would like to know **is there any official portable version** (for windows) at this moment?

I found some 2.91 beta version on [portableapps.com](https://portableapps.com/node/33010) but that's quite outdated...

**Comment by manisandro** [comment]
There are currently no official portable builds, here is a current build:

http://smani.fedorapeople.org/tmp/gImageReader_qt5_3.3.1_x86_64.zip

**Comment by manisandro** [comment]
Portable builds for win64 are now automatically created by the CI build and published to https://github.com/manisandro/gImageReader/releases. Just download gImageReader_qt5_latest_x86_64.zip and run `.../bin/gimagereader-qt5.exe`.

**Comment by brian6932** [comment]
@manisandro Sry for the ping, but I could not find a `.conf` file (with `fd`), or a registry entry regarding the program.
Where is the config stored for portable versions?
