### ISSUE TITLE
spell checker doesn't like contractions with typographical apostrophes

### ISSUE THREAD

**Issue by skierpage** [manisandro/gImageReader#395]
The spell checking in gImageReader (3.3.0 on Fedora 29) is great. But it's confused by the non-ASCII quotation marks that the recognition often produces (see issue #394). For example, in Plain text mode it produced
`CAN‘T DON‘T I‘D I‘LL I‘M I‘VE` (opening left single apostrophe)
`CAN’T DON’T I’D I’LL I’M I’VE` (closing right single apostrophe)
all of which trigger the spell checker's red squiggly line (and right-clicking doesn't offer a sensible replacement). If I change the typographic marks to the plain ASCII typewriter single quotation mark
`CAN'T DON'T I'D I'LL I'M I'VE`
then the red squiggly line goes away for all except I'VE.

It would be nice if the spell checker didn't trip over the default output. For what it's worth Firefox and hunspell command line accept all of those contractions with any of the three marks. except for `I‘VE`.

**Comment by manisandro** [comment]
This behavior comes from qtspell. But I'm not sure I'd actually consider this behavior incorrect. The only reason firefox etc don't complain about `\u2018` and `\u2019` is because they treat it as a word boundary, and only check `CAN`, `DON`, etc, which happen to be correct words. If you check i.e. `WOULDN‘T`, firefox would also complain. Hence I'd argue that it is actually not incorrect to mark these words. Feel free to move the issue to https://github.com/manisandro/qtspell if you want to discuss if futher.
