### ISSUE TITLE
gImageReader-3.3.0 build does not check for podofo

### ISSUE THREAD

**Issue by juanitotc** [manisandro/gImageReader#406]
When configuring gImageReader with cmake, it does not check for the availability of podofo and "make" then fails with:

/usr/src/gImageReader-3.3.0/gtk/src/hocr/HOCRPdfExporter.cc:22:10: fatal error: podofo/base/PdfDictionary.h: No such file or directory
 #include <podofo/base/PdfDictionary.h>

**Comment by manisandro** [comment]
Kinda fixed in ff507d99483fed815a114f25ab14dc4fc103b2c1, but the pkg-config file shipped by podofo-0.9.6 is broken, so it will only work if the respective distro podofo maintainer fixed the pkg-config file (should be ok in debian sid, ubuntu 19.04+, fedora). If the pkg-config detection fails, it reverts to the hardcoded LDFLAGS as before.

**Comment by juanitotc** [comment]
podofo pkg-config file fixed - thanks for the info
