### ISSUE TITLE
gImageReader doesn't correctly locate hunspell dictionaries

### ISSUE THREAD

**Issue by juanitotc** [manisandro/gImageReader#407]
After compiling gImageReader-3.3.0 with --prefix=/usr/local, the system-wide language definitions path is correctly identified at /usr/local/share/tesseract-ocr/4.00/tessdata/

The system-wide spelling dictionaries path is incorrectly identified at /usr/share/hunspell - it should be /usr/local/share/hunspell

In addition, it is not possible to edit either of the above.

**Comment by manisandro** [comment]
It really depends with which prefix enchant and tesseract were compiled. Both paths (spelling and tessdata) are queried from the respective libraries, see

https://github.com/manisandro/gImageReader/blob/master/qt/src/Config.cc#L172

https://github.com/manisandro/gImageReader/blob/master/qt/src/Config.cc#L232

If you link gImageReader against libraries compiled with prefix `/usr`, then the paths will also have `/usr` as prefix, except that for tesseract you can override it by setting the `TESSDATA_PREFIX` env-var.

You cannot edit these paths, since they are read-only paths as returned by the respective libraries.

**Comment by juanitotc** [comment]
I see the code here:

https://github.com/manisandro/gImageReader/blob/master/gtk/src/Config.cc

..but it still seems to erroneously return /usr/share/hunspell

**Comment by manisandro** [comment]
Ah indeed the gtk codebase (currently lagging somewhat behind the qt counterpart) has not yet been ported to use `enchant_get_prefix_dir`, fixed in 4ff852c223cb1ae6092e461b425efa45be83bce4.

**Comment by juanitotc** [comment]
Thanks

**Comment by openelearning** [comment]
Hello,

In Debian 12, if you encounter the problem where no English dictionary or other language dictionaries are detected, it seems to be because gImageReader is searching for /usr/share/myspell. However, if we install myspell, it will remove hunspell. In the gImageReader UI, we can change this to /usr/share/hunspell/, and it works.
