### ISSUE TITLE
Gtk-WARNING **: Unknown property: gtkmm__GtkMenuButton.use-popover

### ISSUE THREAD

**Issue by jarlarntzen** [manisandro/gImageReader#41]
Hi.

I'm starting the gImageReader from terminal just after installing and I'm getting this

    (gimagereader-gtk:8340): Gtk-WARNING **: Unknown property: gtkmm__GtkMenuButton.use-popover

The app starts, though

**Comment by manisandro** [comment]
This depends on which Gtk version is used. The source of the warning is this property in the glade file:

    data/gimagereader.ui:                    <property name="use_popover">False</property>

The glade file targets Gtk 3.8. But since the property is False, it does not actually matter if the gtk version in use does not know about popovers, it does not affect the ui. So this is purely esthetical and not really fixable.
