### ISSUE TITLE
Cannot change default OCR language (French)

### ISSUE THREAD

**Issue by yousefvand** [manisandro/gImageReader#417]
My system:
```
$ lsb_release -a
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.6 LTS
Release:	16.04
Codename:	xenial
```
I have installed `tesseract` and `gimagereader` using these commands:
```
sudo add-apt-repository ppa:alex-p/tesseract-ocr
sudo add-apt-repository ppa:sandromani/gimagereader
sudo pat update
sudo apt install tesseract-ocr tesseract-ocr-eng tesseract-ocr-fas
sudo apt install gimagereader
```
By default `Math / Equations` and `French` are available in OCR language menu and I cannot find out how to add `English` or `Persian` to the menu from `Preferences` so just tried to add them via the only available section in Preferences without any hope.
 
![w](https://user-images.githubusercontent.com/18329462/64185304-27c80100-ce82-11e9-947b-dada1dc39cc6.png)

Then I removed `French` (`sudo apt remove tesseract-ocr-fra`) and started program and `French` was gone from menu (just math/equations left) but after installing it and restarting program even `French` is not in menu anymore.

How to add already installed `tesseract-ocr-language` to program menu?

**Comment by manisandro** [comment]
This is most likely due to the fact that you are not using the stock system tesseract (against which gImageReader was compiled), and hence gImageReader is not picking up the language packs. You need to either recompile gImageReader against tesseract from `ppa:alex-p`, or remove that PPA and use the tesseract packages from the regular ubuntu repositories.
