### ISSUE TITLE
Feature request: Allow user to manually define specific block (region) as "image type"; let him combine blocks while doing this..

### ISSUE THREAD

**Issue by raindropsfromsky** [manisandro/gImageReader#440]
When images are embedded in the source image/pdf, gImageReader tries to read text from the image.
![image](https://user-images.githubusercontent.com/9047168/77838082-f13f3400-718d-11ea-9642-36d0a61cf991.png)

Here, gImageReader has mistaken parts of the left image as four separate text blocks (blocks#1-4). Similarly, Block#10 is also wrongly detected as "text" type, whereas it should be "Image" type.

In such cases, the user has no control.

**Desired:**
- Where a single image is split into multiple blocks (as in case of Blocks#1-4), the user should be able to combine all blocks into one.
- He should be able to manually define any block type as "image". 

**How:** 
Let the user draw a rectangle around the image without disturbing the other blocks that are auto-detected by gImageReader. If gImageReader had auto-detected blocks which are lying partially or fully inside this block, they should be deleted, and replaced by the new manually defined block. 
(In our example, blocks 1-4 should be replaced by a new single block. Let it be numbered as Block#21 (gImageReader had auto-detected 20 blocks on the page, so the next available number is 21).

After this, let the user right-click on the newly created block and choose its type as "image".

In case of block#10, gImageReader has detected the block boundary correctly. So there is no need to correct it. Let the user right-click and choose the block type as "image". The block number remains the same, and only the type changes to "image".

Now gImageReader should be able to export the page with two images and text. The layout of this output page should be the same as the input page.

**Comment by raindropsfromsky** [comment]
In the above example, I pressed CTRL and drew a rectangle (so that the auto0-detected blocks are not disturbed)

The result is, gImageReader has named the new block as block#21.

![image](https://user-images.githubusercontent.com/9047168/77838625-65300b00-7193-11ea-8ad3-8a67296c554b.png)

But it did not delete blocks 1-4, which are fully inside the new block. 
gImageReader should delete the nested blocks automatically.
(In fact, even if a block is partly overlapping, it should be deleted.)

**Comment by manisandro** [comment]
First off, keep in mind that gImageReader does not do any page layout detection or recognition itself, it's all done by tesseract.

The core issue is that as far as I can see, tesseract does not allow you to manually specify a layout to the recognition engine. What you can do is ask tesseract to detect the layout without performing OCR, and that's it (you can scan through the API methods around [1], perhaps I missed something).

The way it works in plain text mode is that the layout is queried from tesseract, then the user can manually adjust the layout as desired (adjusting areas, right-clicking areas do change the order or to delete them, or adding new ones with CTRL+drag), after which gImageReader will extract subimages for each selected area and process these independently. This is easy to do in plain text mode since the output is just text and does not contain any layout information.

In hOCR+PDF mode such an approach is not as easy, because after performing OCR on the subimages, you'd have to re-assemble these while recomputing all the layout information to be correct with respect to the full page size. This is not impossible to do, but less trivial than in plain text mode.

The overall question (regarding hOCR+PDF mode) is whether it's worth the trouble to implement. Typically the issue is that image areas are misdetected as text. You can just drop these from the hOCR tree and manually add a graphic region instead (which you can do by right-clicking a page item in the tree). Unless I'm missing something, this gives you the same result as declaring the area as image beforehand.

[1] https://github.com/tesseract-ocr/tesseract/blob/master/include/tesseract/baseapi.h#L491

**Comment by manisandro** [comment]
I'll defer this to tesseract.
