### ISSUE TITLE
Scanner not recogised

### ISSUE THREAD

**Issue by achimwagenknecht** [manisandro/gImageReader#48]
Windows 10, Gimp reads images from scanner without problem.

**Comment by manisandro** [comment]
Sorry but with so litte information it is impossible for me to understand what is the problem.

**Comment by achimwagenknecht** [comment]
When installing the internationalized version, this problem is gone, too! Thanks again!

**Comment by manisandro** [comment]
Really should not depend on localized on not, but glad it works.

**Comment by bmix** [comment]
Same problem here. Scanner is not recognized under Windows 10 Home. Version is _gImageReader 3.1.99_, localized version. I just tried to start it as Administrator, no luck either. Error message is: "No scanners found". I don't have Gimp installed, so I can not confirm, whether it recognizes it. However, the other apps I am using, see it.

What other information do you need?

**Comment by manisandro** [comment]
Here is what I'll publish in the FAQ as soon as 3.2.0 is released (the reason for the delayed publishing being that 3.1.99 erroneously blocks the 32bit installer from running on a 64bit system, which I've fixed in master and hence for 3.2.0, but I didn't want to publish misleading info):

** My scanner is not detected (Windows) **
On Windows, gImageReader uses TWAIN for communicating with scanners. gImageReader implements the TWAIN 2.2 specification, and supports both TWAIN 1.x and TWAIN 2.x data sources (drivers). Typically, there are two main causes which leads to a scanner not being recognized under Windows:
1. **There is no TWAIN driver installed for the scanner:** TWAIN drivers should be installed in `C:\WINDOWS\twain_32` or `C:\WINDOWS\twain_64`. Check these locations whether there are any drivers related to your scanner, resp. check the manufacturers website whether they offer a TWAIN driver for download.
2. **TWAIN driver architecture mismatch:** If your scanner ships a 32bit TWAIN driver (i.e. installed in `C:\WINDOWS\twain_32`), then you'll need to use the 32bit version of gImageReader. If your scanner ships a 64bit TWAIN driver, you'll need to use the 64bit version of gImageReader.


Check if any of these scenarios might apply to your setup.

**Comment by bmix** [comment]
Just found your answer now.
Ok, so I am running a 64bit OS (Win10) and the TWAIN for my scanner is 32bit. 

Just to make sure, I uninstalled gImageReader and re-installed it using: `gImageReader_3.1.99_qt5_x86_64.exe`. It went to `C:\Program Files (x86)\gImageReader`, which should mean, it is 32bit. AFAIK the 64bit should go to `C:\Program Files\gImageReader` while the 32bit should go to `C:\Program Files (x86)\gImageReader`. 

Since there is a x86 in the installer-file-name I am a little insecure now, since I am used to the `x86` signature designating a 32bit version. So I thought, that there may be two versions in the installer and it chooses the architecture's preferred one. In the version-string in the About-dialog there is no architecture named.

The x686-version you offer did not want to install. Architecture mismatch.

**Comment by manisandro** [comment]
Ah indeed it looks like even the 64bit version installs to `Program Files (x86)`. I'll need to look at the installer script to fix that.

The i686 3.1.99 release does indeed refuse to install on a 64bit system, which is should not. I'm hoping to release 3.2.0 by next weekend (which allows 32bit installs on 64bit systems again). In the meantime, you can use this snapshot build:

https://smani.fedorapeople.org/tmp/gImageReader_3.1.99_qt5_i686.exe

Hope this helps.

**Comment by bmix** [comment]
The 64-bit version of release 3.2.0 still installs into `Program Files (x86)`.

On a sidenote: Why not adding the 32-bit or 64-bit designation to the "About" dialog?

Another sidenote (I do not want to open a new issue, since I do not remember correctly, how I had the tessdata files installed): Instead of having set alternative install-locations for the dictionaries and tessdata, I had a symlink or junction (Win10) to `C:\Program Files (x86)\Tesseract-OCR\tessdata`. After uninstallation of `gImageReader-x64` they were gone. But I am not a 100% sure. I may have had them also in another path, but linked. Anyway, now they are gone (which is not bad, since I re-installed current Tesseract-OCR, but people may have their own datafiles authored and, maybe, somebody symlinks them, too, you never know...).

**Comment by manisandro** [comment]
Hmm I'll need to revisit the (x86) thing.

About the files which were removed: the installer does the following when updating an existing installation:
- Back up all the files in `%ProgramFiles%\gImageReader\share\tessdata` to a temporary location
- Perform the uninstall (which removes everything below and including `%ProgramFiles%\gImageReader`)
- Copy back the backed up files to the new install `%ProgramFiles%\gImageReader\share\tessdata`

I'm not actually sure what happens during uninstall when `%ProgramFiles%\gImageReader\share\tessdata` is a symlink, I fear it may indeed happend that instead of merely deleting the symlink, it deletes all files below the symlink destination and then the symlink. But I'd expect the old files to reappear after the new install under `%ProgramFiles%\gImageReader\share\tessdata` (which should then not be a symlink, but a regular folder).

**Comment by tika949898** [comment]
Scanner is not recognized under Windows pro 10 . What should I do? I am using canon scanner.

**Comment by anvish2** [comment]
Is there a 32-bit version of gImageReader? Both *_qt5_x86_64.exe and *_qt5_x86_64_portable.zip seem to contain only 64-bit version executables.
