### ISSUE TITLE
possible enhancement: add another OCR engine to gImagereader

### ISSUE THREAD

**Issue by narayaan** [manisandro/gImageReader#52]
First of all, thanks a lot for this nice program!

It would be nice if there was an ability to use another open source OCR engine (like Ocrad or  CuneiForm) within gImagereader. This would especially be helpfull when the output of two engines can be compared to get a lower error rate in bigger texts.

**Comment by manisandro** [comment]
This will require some work, since currently much of the language handling is centered around tesseract tessdata language names. My first big priority is to polish the ongoing work of the past half year and finally push out a new release. If you want to give this a shot, happy to accept pull requests.

**Comment by manisandro** [comment]
Closing since I realistically won't have the intention to work on this. Considering that tesseract is pretty much the best open source engine around I don't see benefit of being able to use other engines justify the effort of overhauling the various tesseract-centered components of the program.
