### ISSUE TITLE
tesseract 5

### ISSUE THREAD

**Issue by joneldiablo** [manisandro/gImageReader#574]
Hi guys, we can't configure the new path for tesseract 5 for languages "/usr/share/tesseract-ocr/5/tessdata" new one.
Linux Mint 20.2 Uma

**Comment by manisandro** [comment]
What do you mean? gImageReader asks tesseract for the data path via `tesseract::TessBaseAPI::GetDatapath`, alternatively you can set the env-var TESSDATA_PREFIX.

**Comment by invasi0n** [comment]
@joneldiablo probably you don't have the latest version, 3.4.0. I just blindly did an sudo apt-get install -y gimagereader and got the previous version which uses the path for tesseract 4.

**Comment by invasi0n** [comment]
I also have this problem.

![Screenshot-202202230028-1666x671](https://user-images.githubusercontent.com/10316162/155230428-e2778744-f8c0-4536-b389-f72a02fa7c78.png)
![Screenshot-202202230031-563x159](https://user-images.githubusercontent.com/10316162/155230631-60a9bba0-ca65-4849-813d-fe25d99976cc.png)
![Screenshot-202202230029-520x571](https://user-images.githubusercontent.com/10316162/155230461-a5b18705-5145-403b-93b8-bc041e29c93e.png)
![Screenshot-202202230029-476x437](https://user-images.githubusercontent.com/10316162/155230452-1d31da1f-40e7-4f6c-80ee-4d1d588c37f6.png)

**Comment by manisandro** [comment]
The build in the PPA is compiled against libtesseract4-4.1.1-2build2 as shipped in the standard ubuntu focal repositories. If you want to use tesseract 5, you'll need to recompile gimagereader against it.

**Comment by invasi0n** [comment]
Ok, thanks again!

**Comment by derrikF** [comment]
Hello

in openSUSE_Tumbleweed, gImageReader doesn't want to work with tesseract5

the screenshot shows that I have tesseract5 installed
![1](https://user-images.githubusercontent.com/4710022/205879767-232d8649-6469-49c7-8bae-15a0fa74b56d.png)

Next, I install the package from the link https://download.opensuse.org/repositories/home:/sandromani/openSUSE_Tumbleweed/x86_64/gimagereader-qt-3.4.0-10.28.x86_64.rpm

but the installer requires you to install libtesseract4 as shown in the screenshot
![2](https://user-images.githubusercontent.com/4710022/205880313-2e20bdf0-8409-4bff-9611-bdf7b9559748.png)

why do I need libtesseract4 if I already have libtesseract5 ?

after installing, gImageReader doesn't see tesseract5

libtesseract4 cannot be deleted, because gImageReader is also deleted

And what should I do? because even your official package doesn't see tesseract5
