### ISSUE TITLE
Crash on Windows 10 with Hungarian text

### ISSUE THREAD

**Issue by robertbus** [manisandro/gImageReader#59]
Hi Sandro,

First of all gImageReader is a great application, thanks for doing it!

I found that [version 3.1.2](https://github.com/manisandro/gImageReader/releases/download/v3.1.2/gImageReader_3.1.2_qt5_i686.exe) on Windows 10 works fine with English, but it constantly crashes if I try to use it on Hungarian text.

I installed the Hungarian [language definition](https://github.com/tesseract-ocr/tessdata/blob/master/hun.traineddata) and the [spelling](https://cgit.freedesktop.org/libreoffice/dictionaries/tree/hu_HU/hu_HU.aff) [dictionary](https://cgit.freedesktop.org/libreoffice/dictionaries/tree/hu_HU/hu_HU.dic) files as suggested in the manual page.

The crash happened on a PDF file which contained a scanned paper. However I could reproduce the issue with a [screenshot of a Hungarian article](https://cloud.githubusercontent.com/assets/14806588/14233489/925e6c6a-f9ca-11e5-9f31-74453601e54a.png) as well.

Here are the logs:
[crash_handler.txt](https://github.com/manisandro/gImageReader/files/201425/crash_handler.txt)
[gimagereader.log.txt](https://github.com/manisandro/gImageReader/files/201424/gimagereader.log.txt)
[twain.log.txt](https://github.com/manisandro/gImageReader/files/201426/twain.log.txt)

Then I tried to use the [alternative build](https://github.com/manisandro/gImageReader/releases/download/v3.1.2/gImageReader_3.1.2_qt5_i686_tesseract3.04.00.exe) with the same Hungarian language definition and spelling dictionary files. I got the following error popup window:

![error_popup](https://cloud.githubusercontent.com/assets/14806588/14233753/c648d072-f9d1-11e5-9bbd-9a696ec5b52a.png)

And the following log files:
[gimagereader_alternative.log.txt](https://github.com/manisandro/gImageReader/files/201460/gimagereader_alternative.log.txt)
[twain_alternative.log.txt](https://github.com/manisandro/gImageReader/files/201461/twain_alternative.log.txt)

Thanks,
Robert

**Comment by manisandro** [comment]
Hi Robert

First, when using the language definitions from https://github.com/tesseract-ocr/tessdata/, you will need to use the build for tesseract 3.04.00, as previous tesseract versions (as the one the original 3.1.2 build uses) crash when used with newer traineddata files.

That said, make sure that you have downloaded the actual taineddata binary blob (as opposed to the github html page), specifically that you used the following url to download the traineddata:

https://github.com/tesseract-ocr/tessdata/raw/master/hun.traineddata

(The downloaded hun.traineddata should be around 11.6 MB).

If things are still crashing, I'll post a build with complete debug symbols, so that we can check where exactly the crash is happening.

Hope this helps
Sandro

**Comment by robertbus** [comment]
Hi Sandro,

It was my bad. I used the wrong version of the traineddata. 
Sorry for the false alarm and thank you for your help!

Regards,
Robert
