### ISSUE TITLE
crash recovery

### ISSUE THREAD

**Issue by nysherpa** [manisandro/gImageReader#604]
I can't find any information at http://soppalco.ovunque-si.it/documentazione/linux/gimagereader/ on crash-recover, particularly how to use the gImageReader_crash-save,txt gimageReader created just now when it crashed. Without this info users' have to start over after every crash. The book I was OCRing is over 600 pages long...

**Comment by manisandro** [comment]
The `gImageReader_crash-save.txt ` file contains what has been recognized up to the point it crashed:
- When recognizing in plain text mode, it just contains plain text. You can open it in any text-editor or just paste the contents back into the gImageReader text output pane to continue your work.
- When recognizing in hOCR mode, it contains HTML markup. You can change the file extension to HTML and open it in the gImageReader hOCR output pane to continue your work.

Fair point that the hOCR crash save file extension should be `html` rather than `txt`, I've fixed this in ab76d6f12671d5ee83fd42bee6843ec496d8343f.
