### ISSUE TITLE
[Bug] The program fails to install certain dictionaries

### ISSUE THREAD

**Issue by tyrell-wallace** [manisandro/gImageReader#656]
As I was testing out some different languages, I noticed that the program fails to install certain dictionaries. In my case, I tested Japanese, Chinese Traditional, Chinese Simplified, Spanish and German.

The program managed to install dictionaries for Spanish and German, but failed to do so for Japanese and Chinese (simplified and traditional).

This is related to https://github.com/manisandro/gImageReader/issues/650 and https://github.com/manisandro/gImageReader/issues/649. I didn't get the same error as #649 though. It just says "No spelling dictionary found for  *language*" in my case. Running as administrator doesn't help, either. Also unlike #649, I only have a "hunspell" folder (and not a "myspell" one).

------------------------------------------------

If it helps, I'm running the x64 Portable on Windows 10 22H2. I've noticed I and the 2 other users are running Windows, so it might be an OS-specific issue. My guess is that the names of the dictionaries that failed to install on whatever source the program is getting them from has changed.

**Comment by Wedierstrass** [comment]
How do you manage to install the spanish dictionary? I tried installing it directly from the button on gimagereader, it poops up the message saying that the instalation was succesful, but the dictionary isn't detected.
If it helps I'm in Windows 10 pro x64 22H2 and I have also tried downloading directly the dictionary from here: https://cgit.freedesktop.org/libreoffice/dictionaries/tree/es and even changing the file names to spa instead of es_ES. (The original files seems to come from this page: https://github.com/sbosio/rla-es and the "_ES" refers to the regional version from Spain)

**Comment by tyrell-wallace** [comment]
Hi @Wedierstrass, I managed to install the spanish language and all related dictionaries with no issue on the latest x64 portable for windows and on the version I had tested before. It doesn't give me any errors on that step.

Now, when things get weird:

On the GTK version, the program gave me the same error as before, and produced a crash log with nothing inside it. 
On the qt5 version however, it only installed the Argentinian dictionary, but unlike the gtk version, it actually worked. It also worked with German, and with the same behaviour: it installed only one specific dictionary, unlike the GTK and previous version that installed many.

**Comment by tyrell-wallace** [comment]
Give it a try with the latest qt5 version and see what happens.

**Comment by manisandro** [comment]
Should be fixed with https://github.com/manisandro/gImageReader/commit/a4820ebb8f8f05086f11c310c3f55a6ff5903f3e

**Comment by tyrell-wallace** [comment]
I'll test it
