### ISSUE TITLE
Panes buttons to be highligted on mouse over

### ISSUE THREAD

**Issue by CharlesNepote** [manisandro/gImageReader#97]
On the top menu bar, all buttons are highlighted when mouse come over each one.
On the file pane, the button "Add image" is also highlighted when the mouse come over it.
But other buttons, from both the "file" pane and the "output" pane are not highlighted. It takes several days for me to discover that I could click on the "post-processing tools button" ;) May be I am not very smart :( but there should be a sign for each button to let people know they can click on it.

#notveryurgent

**Comment by manisandro** [comment]
Uhm, but the border of the button changes depending on whether you are hovering on it or not, so there already is feedback?

**Comment by CharlesNepote** [comment]
With gImageReader-gtk the border of some buttons doesn't change. I can publish a screenshot if you want.

**Comment by manisandro** [comment]
I'd say this is more an issue with your gtk theme than with the application. With the standard Adwaita gtk theme, there is plenty of visual feedback when hovering an icon. And now that I check, the icon images themselves are even highlighted when hovering over them. Closing this since it is a theme issue.
